Актуализация правил ЛОРа
maxcom/lorsource pull request #954
Opened 2021-06-30 16:24 UTC by 7dr1v3

По мотивам https://www.linux.org.ru/forum/linux-org-ru/16395361

После деплоя https://www.linux.org.ru/forum/linux-org-ru/12716113 - потеряет актуальность

2021-07-01 11:38 UTC, bookwar requested changes

2021-07-01 11:38 UTC, bookwar commented on src/main/webapp/help/rules.md
> +  - [Talks](https://www.linux.org.ru/forum/talks/) ограничен на чтение для пользователей чей рейтинг ниже 50.
"ограничен на чтение"  - звучит непонятно. Я бы написала как-то наподобие "Писать в раздел Talks могут только пользователи с рейтингом больше 50"

2021-07-01 11:38 UTC, bookwar commented on src/main/webapp/help/rules.md
> +Если вы хотите сообщить об ошибке в работе сайте, это можно сделать в [официальном репозитории](https://github.com/maxcom/lorsource/issues).
"в работе движка сайта" ?

2021-07-01 11:55 UTC, 7dr1v3 commented on src/main/webapp/help/rules.md
> +Если вы хотите сообщить об ошибке в работе сайте, это можно сделать в [официальном репозитории](https://github.com/maxcom/lorsource/issues).
это вроде как и так очевидно, но добавить не проблема так что ок

2021-07-01 11:55 UTC, 7dr1v3 commented on src/main/webapp/help/rules.md
> +  - [Talks](https://www.linux.org.ru/forum/talks/) ограничен на чтение для пользователей чей рейтинг ниже 50.
Идея в том что бы был список разделов и с права к каждому в чем ограничение, просто удобство восприятия, по этому нужно  "Talks - [описание ограничения]" 

можно "Talks - пользователи с рейтингом ниже 50 не могут добавлять комментария"

2021-07-01 12:11 UTC, 7dr1v3 commented on src/main/webapp/help/rules.md
> +  - [Talks](https://www.linux.org.ru/forum/talks/) ограничен на чтение для пользователей чей рейтинг ниже 50.
остановился пока на ` - для пользователей с рейтингом ниже 50, доступен только на чтение.` вроде получилось понятнее сформулировать.

2021-07-01 16:46 UTC, tazhate reviewed
Всё отлично я считаю

2021-07-02 10:07 UTC, merged

2021-07-13 08:41 UTC, abitrolly commented on src/main/webapp/help/rules.md
> +пользователям которым нужно "отдохнуть от форума", после чего их будут рады снова увидеть на форуме.
будут рады увидеть снова.